export const CREATE_LESSON = 'CREATE_LESSON';
export const LOAD_LESSONS_SUCCESS = 'LOAD_LESSONS_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_LESSON_SUCCESS = 'CREATE_LESSON_SUCCESS';
export const UPDATE_LESSON_SUCCESS = 'UPDATE_LESSON_SUCCESS';

export const LOAD_LESSON_SUCCESS = 'LOAD_LESSON_SUCCESS';
export const ADD_LESSON_SUCCESS = 'ADD_LESSON_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOAD_LANGUAGES_SUCCESS = 'LOAD_LANGUAGES_SUCCESS';

export const LOAD_PHRASES_SUCCESS = 'LOAD_PHRASES_SUCCESS';
export const ADD_LAST_VALUE_SUCCESS = 'ADD_LAST_VALUE_SUCCESS';

export const LOAD_PHRASE_USES_SUCCESS = 'LOAD_PHRASE_USES_SUCCESS';

export const LOAD_EXAMPLES_SUCCESS = 'LOAD_EXAMPLES_SUCCESS';

export const SET_OBJECT_TO_SEND = 'SET_OBJECT_TO_SEND';
export const SAVE_PAIR_SUCCESS = 'SAVE_PAIR_SUCCESS';